#server:
#  port: 9000
#  
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:8900/eureka/
#      
#spring:
#  application:
#    name: daoservice
#
#mybatis:
#  type-aliases-package: com.wtl.DAOService.Entity
#  mapper-locations:
#  - classpath:/com/bioFish/DAOService/dao/*/*.xml
#  config-location: classpath:mybatis-config.xml
#
#mysql: 
#  datasource: 
#     readSize: 1  #读库个数
#     type: com.alibaba.druid.pool.DruidDataSource
#     mapperLocations: classpath:/com/bioFish/DAOService/dao/*/*.xml
#     configLocation: classpath:mybatis-config.xml
#     write: 
#       url: jdbc:mysql://192.168.1.126:3306/WTL_SAAS?characterEncoding=utf8&useSSL=false&useUnicode=true
#       username: WTL
#       password: WTL82823777
#       driver-class-name: com.mysql.jdbc.Driver
#       minIdle: 5
#       maxActive: 100
#       initialSize: 10
#       maxWait: 60000
#       timeBetweenEvictionRunsMillis: 60000
#       minEvictableIdleTimeMillis: 300000
#       validationQuery: select 'x'
#       testWhileIdle: true
#       testOnBorrow: false
#       testOnReturn: false
#       poolPreparedStatements: true
#       maxPoolPreparedStatementPerConnectionSize: 50
#       removeAbandoned: true
#       filters: stat
#     read: 
#       url: jdbc:mysql://192.168.1.126:3306/WTL_SAAS2?characterEncoding=utf8&useSSL=false&useUnicode=true
#       username: WTL
#       password: WTL82823777
#       driver-class-name: com.mysql.jdbc.Driver
#       minIdle: 5
#       maxActive: 100
#       initialSize: 10
#       maxWait: 60000
#       timeBetweenEvictionRunsMillis: 60000
#       minEvictableIdleTimeMillis: 300000
#       validationQuery: select 'x'
#       testWhileIdle: true
#       testOnBorrow: false
#       testOnReturn: false
#       poolPreparedStatements: true
#       maxPoolPreparedStatementPerConnectionSize: 50
#       removeAbandoned: true
#       filters: stat
#       
#
#logging:
#  level:
#    root: INFO
#    com.bioFish: DEBUG