server:
  port: 9110
  
eureka:
  instance:
    hostname: localhost
    status-page-url-path: http://${eureka.instance.hostname}:8900/info
    health-check-url-path: http://${eureka.instance.hostname}:8900/health
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8900/eureka/

spring:
  application:
    name: userservice
    
user:
  DAOServicePath: http://daoservice/
  RedisServicePath: http://redisservice/
  KafkaServicePath: http://kafkaservice/