server:
  port: 8400
  
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8900/eureka/

spring:
  application:
    name: kafkaservice
  kafka:
    bootstrap-servers:
    - 192.168.1.126:9092
    consumer:
      group-id: saas-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      
      
logging:
  level:
    root: info

      