server:
  port: 8500
  
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8900/eureka/
      
spring:
  application:
    name: redisservice
  redis:
    database: 0
    host: 192.168.1.126
    port: 6379
    password: 
    pool:
      max-active: 10
      max-wait: -1
      max-idle: 10
      min-idle: 0
    timeout: 200