server:
  port: 9000
  
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8900/eureka/
      
spring:
  application:
    name: daoservice
  datasource:
    url: jdbc:mysql://192.168.1.126:3306/WTL_SAAS?characterEncoding=utf8&useSSL=false
    username: WTL
    password: WTL82823777
    driver-class-name: com.mysql.jdbc.Driver
    
mybatis:
  type-aliases-package: com.wtl.DAOService.Entity
  mapper-locations:
  - classpath:mapper/*.xml

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.wtl: DEBUG